#!/usr/bin/env bash

REQS=${CI_WORKSPACE}/testpack/requirements.txt
if [ -f ${REQS} ]; then
    echo "  Attempting to install python modules"
    pip3 install --upgrade pip
    pip3 install -r ${REQS}
else
    echo "  No python modules to install"
fi
