#!/usr/bin/env bash

if [ $UID -ne 0 ]; then
    PIP="sudo /usr/local/bin/pip3"
else
    PIP=pip3
fi

REQS=${CI_WORKSPACE}/testpack/requirements.txt
if [ -f ${REQS} ]; then
    echo "  Attempting to install python modules"
    ${PIP} install -qr ${REQS}
else
    echo "  No python modules to install"
fi
